services:
  - type: web
    name: hamro-krishi-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18.18.0"
      - key: PORT
        value: "3000"
